### ISSUE TITLE
Measurement table width can fall off the page

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#124]
In GitLab by @nwalczak on Oct 2, 2019, 10:12

The width of the columns for the measurement table is set, but the total width can fall of the page, which can be akward.  We should see if there's some way to determine page width and limit table width based on that.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Oct 7, 2019, 10:29

assigned to @nwalczak

**Comment by mwes** [comment]
In GitLab by @nwalczak on Oct 18, 2019, 09:47

created branch [`123-measurement-table-width-can-fall-off-the-page`](https://gitlab.sd2e.org/sd2program/experimental-intent-parser/compare/develop...123-measurement-table-width-can-fall-off-the-page)

**Comment by mwes** [comment]
In GitLab by @nwalczak on Oct 18, 2019, 09:47

mentioned in merge request !72

**Comment by mwes** [comment]
In GitLab by @nwalczak on Oct 18, 2019, 10:05

I'm not having a ton of luck with this one.  The problems basically revolve around the documentation being shoddy and not having the right functions/controls that I need.

By editing the table in the document I can make it so the table ignores margins, however I don't see any way within GAS to control the location of the table in the document.  It seems like you can only do that through the editor.

I thought that maybe I could figure out a way to keep the table within the paragraph area by getting the page width and then reverse engineering the margin sizes.  This was based on these two functions:

https://developers.google.com/apps-script/reference/document/body#getpagewidth

https://developers.google.com/apps-script/reference/document/table#setColumnWidth(Integer,Number)

However, despite the documentation saying that both those functions are in "points", in practice I found that the page width is 612 and if I create a table with a total column width of 77, I get a table that's just at the edge of the page.

It looks like further work will have to be done to figure out just how wide the table can be.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Oct 23, 2019, 16:03

removed assignee

**Comment by mwes** [comment]
In GitLab by @jakebeal on Oct 25, 2019, 09:43

Switching pages to 11x17 landscape seems to pretty much handle this for most tables.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Oct 25, 2019, 10:17

Remaining question: do we want to do this programmatically, or just ask people to do that?

**Comment by jakebeal** [comment]
This is obsolete: 11x17 landscape seems to handle this sufficiently well.
