### ISSUE TITLE
Create mechanism to allow links for media components

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#134]
In GitLab by @nwalczak on Oct 21, 2019, 11:24

In the measurements table all of the columns to the left of measurement type are considered to be reagents.  These can be compounds added to the experiment but can also define the media used.  The reagents were designed to have the reagent name in the column header and then table cells have a comma separated list of the fluid measurements for different amounts of the reagent to be added.

Media is slightly different, where the column header is expected to be media, and the comma separated list can specify the type of media as well as the fluid measurement.

We need to update how the media column is parsed, so that we can parse links in the media name and also parse fluid measurements.  Currently, we don't use the link information and we only look for the media name and not the fluid amount.

**Comment by mwes** [comment]
In GitLab by @nwalczak on Oct 21, 2019, 12:21

Good input sheet for this is here: https://docs.google.com/document/d/13tJ1JdCxL9bA9x3oNxGPm-LymW91-OT7SRW6fHyEBCo/edit

**Comment by mwes** [comment]
In GitLab by @jakebeal on Nov 11, 2019, 10:21

assigned to @tramyn

**Comment by mwes** [comment]
In GitLab by @jakebeal on Apr 27, 2020, 09:14

Need to be negotiated with @mweston ; for generalization we should make the handling of all reagents uniform and not assuming backend resolution for some but not other, but will need to make sure this doesn't break things during transition.

**Comment by mwes** [comment]
In GitLab by @mweston on Apr 28, 2020, 08:57

FYI there's no actual distinction here in the *target* generated format: media is a content element, just like an inducer, antibiotic, PBS, or anything else we can specify against sample. Per the schema, this value can be numeric or a string, and a unit specification is optional.

The distinction that arises here is that instead of specifying a volume and unit of the media, we're just specifying the name. The volume is handled by the Strateos protocol parameters: https://gitlab.sd2e.org/sd2program/experimental-intent-parser/issues/177

So I think the backend should not make a special case here. Regardless of the column provided, it can:
- Parse the column, and use the URI link provided
- Parse the values, which an either be numeric + unit, or a string value (this seems to be the crux of the above comment)

The current IP can now handle these cases just fine, but I am happy to discuss changes here.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Apr 29, 2020, 07:40

@mweston That's good to know: we'll plan accordingly.

**Comment by tramyn** [comment]
@mwes I believe IP supports this. Could you confirm?

**Comment by mwes** [comment]
Hi @tramyn - yes this is currently supported.
