### ISSUE TITLE
Support "@ hour" in template creation as well

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#143]
In GitLab by @jakebeal on Oct 25, 2019, 09:51

To help people get "@ hour" columns right, it would be nice if the generate measurement table dialog box gave an option to have "@ hour" information, e.g., instead of "12 reagents" allow "3 reagents at 4 time points"

**Comment by tramyn** [comment]
@mwes I need more information about this feature request. What would you like IP to generate in a measurement table when specifying "3 reagents at 4 timepoints"? I have created 3 types of measurement table templates in this document [here](https://docs.google.com/document/d/1JNdhNm9iVezFzDE1q6ofJcMn2-3mEhExP6ggtKCZcHI/edit?usp=sharing) that IP can generate for this request. Does any of these options fit what you want supported?

**Comment by jakebeal** [comment]
@tramyn This is actually from me, not @mwes ; he's just identified due to the transfer.

In the examples you've got the second form following how I'd been thinking about it.
