### ISSUE TITLE
Catalog failure errors are obscure

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#147]
In GitLab by @jakebeal on Oct 30, 2019, 10:35

This appears to be an error from the document not being in the catalog:

> Validation Failed! Schema Validation Error: 'YeastSTATES-CRISPR-growth-cruves' is not one of ['UNKNOWN']  Failed validating 'enum' in schema[0]:     {'enum': ['UNKNOWN'], 'type': 'string'}  On instance:     'YeastSTATES-CRISPR-growth-cruves'  

However, there is nothing there that would lead one to understand that the problem is that the document is not listed correctly in the catalog. This error message thus needs to be improved.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Nov 11, 2019, 10:19

assigned to @tramyn

**Comment by mwes** [comment]
In GitLab by @tramyn on Nov 20, 2019, 10:15

@jakebeal could you provide me an example that will replicate this issue? I am unsure how to reproduce this bug.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Nov 20, 2019, 10:36

Here's one: https://docs.google.com/document/d/1Qsw2JBfF75gOyWpbSrlC9SuHYBiV8f-lK_5pF1I3rww/edit?usp=sharing

**Comment by mwes** [comment]
In GitLab by @tramyn on Nov 25, 2019, 11:33

created branch [`146-catalog-failure-errors-are-obscure`](/sd2program/experimental-intent-parser/compare/develop...146-catalog-failure-errors-are-obscure) to address this issue

**Comment by mwes** [comment]
In GitLab by @mweston on Nov 25, 2019, 14:16

The above file is failing because the file is not in a directory which automatically provides its Challenge Problem enumeration (YeastStates, Novel Chassis, etc.). The generation defaults to "Unknown" which is not a valid challenge problem, so it correctly fails validation. For this particular instance of a validation error (there can be many others), the solution is to place the request document in a relevant challenge problem folder.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Dec 9, 2019, 10:47

Problem: the JSON schema validator is giving a unified message, and pulling the information out may be complicated. Thus, pushing this back to 2.5 in order to prioritize parameter tables.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Dec 9, 2019, 10:48

https://python-jsonschema.readthedocs.io/en/stable/errors/#jsonschema.exceptions.ValidationError

**Comment by tramyn** [comment]
I believe this issue has been addressed. @mwes are there additional changes you want IP to support for handling error message for validation?

**Comment by mwes** [comment]
Hi @tramyn, per testing, this is still unresolved, with the base case still reproducible. Any experiment requests not in a directory that automatically provides its Challenge Problem enumeration (YeastStates, Novel Chassis, etc.) will fail. The generation defaults to "Unknown", which is not a valid challenge problem, so it correctly fails validation. For this particular instance of a validation error (there can be many others), the solution is to place the request document in a relevant challenge problem folder, but the users do not/cannot know to do that to fix the issue.

To reproduce:
1. Take any experiment request document
2. Make a copy of it
3. Move it out of one of the request folders: Novel Chassis, YeastStates, etc.
4. Try to generate or validate it

The Google Docs validate call returns:

![image](https://user-images.githubusercontent.com/5033275/87313444-e1a2eb80-c4ef-11ea-9dd8-6905c34380a7.png)

```
Message details
Exception: Request failed for http://intentparser.sd2e.org returned code 500. Truncated server response: Internal Server Error (use muteHttpExceptions option to examine full response)
```

Running the intent parser directly or running the generate call e.g.

```
http://intentparser.sd2e.org/document_request?1-S2qjbDjakh1nmDakqDXkcZmHP437UFpGyNGH49Kx5c
```

shows the underlying error is still the same (see below). A better interpretation of this that helps the user understand and resolve the issue: "The Intent Parser cannot determine which Challenge Problem this Experiment Request Document is associated with. Is this document in a Challenge Problem folder under DARPA SD2E Shared > CP Working Groups > ExperimentalRequests?"

![image](https://user-images.githubusercontent.com/5033275/87313944-9937fd80-c4f0-11ea-86f7-417ea703013e.png)

```
 'Unknown' is not one of ['NOVEL_CHASSIS', 'INTENT_PARSER_TEST', 'MOSQUITO_RELATEDNESS_INFERENCE', 'BIOCON', 'CELL_GROWTH', 'PROTEIN_DESIGN', 'YEAST_STATES', 'RIBOSWITCHES', 'UNDEFINED']

Failed validating 'enum' in schema['properties']['challenge_problem']:
    {'$comment': 'version: 2.2.0#master; generated: 20200310T152056+00:00; '
                 'source: '
                 'git@github.com:SD2E/python-datacatalog.git@4aeb62a',
     '$id': 'https://schema.catalog.sd2e.org/schemas/challenge_problem_id.json',
     '$schema': 'http://json-schema.org/draft-07/schema#',
     'additionalProperties': False,
     'description': 'Challenge problem enumeration',
     'enum': ['NOVEL_CHASSIS',
              'INTENT_PARSER_TEST',
              'MOSQUITO_RELATEDNESS_INFERENCE',
              'BIOCON',
              'CELL_GROWTH',
              'PROTEIN_DESIGN',
              'YEAST_STATES',
              'RIBOSWITCHES',
              'UNDEFINED'],
     'examples': ['NOVEL_CHASSIS',
                  'INTENT_PARSER_TEST',
                  'MOSQUITO_RELATEDNESS_INFERENCE',
                  'BIOCON',
                  'CELL_GROWTH',
                  'PROTEIN_DESIGN',
                  'YEAST_STATES',
                  'RIBOSWITCHES',
                  'UNDEFINED'],
     'title': 'Challenge Problem Id',
     'type': 'string'}

On instance['challenge_problem']:
    'Unknown' 
```

Users have generally been trained to create their requests accordingly, but new users still run into this, and previous users sometimes forget.

**Comment by tramyn** [comment]
Okay, then it looks like this issue is best classified under milestone 2.8 (cleaning up known UI issues).

**Comment by mwes** [comment]
Sounds good to me.

**Comment by tramyn** [comment]
@jakebeal for this issue, does it make sense for IP to generate a default challenge problem or would you rather stick with your original request to have IP report a human readable error and have the user check where their document is located in SD2 Google Drive folder?

**Comment by tramyn** [comment]
@mwes I noticed that [data catalog](https://schema.catalog.sd2e.org/schemas/challenge_problem_id.json) accepts an "UNDEFINED" value when validating a SR challenge problem. When will a challenge problem get classified as "UNDEFINED"? Should a document not located in the desired SD2 folder be treated similarly to documents that are in the SD2 experiment request folder and have its challenge problem assign to "UNDEFINED"?

**Comment by mwes** [comment]
@tramyn the mapping function you're using either populates a successful challenge problem mapping or it does not - the success is binary. It does not return `UNDEFINED` - this is a placeholder value in the enumeration we don't use. 

`Unknown` looks like a default that is coming from the intent parser and is not a valid value, hence the schema validation error: https://github.com/SD2E/experimental-intent-parser/blob/master/intent_parser/intent_parser.py#L342

This is an error condition and can only be fixed by user action. We should not proceed with any additional parsing or return something that could be attempted to be used - without the challenge problem and experiment_reference we have no context for the experiment request. Filling in `UNDEFINED` won't solve the problem unfortunately, it will just silently delay it. 

A better interpretation of this that helps the user understand and resolve the issue is to return an error that says something to the effect of: "The Intent Parser cannot determine which Challenge Problem this Experiment Request Document is associated with. Is this document in a Challenge Problem folder under DARPA SD2E Shared > CP Working Groups > ExperimentalRequests?"
