### ISSUE TITLE
Report pipeline status and errors in document

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#171]
In GitLab by @jakebeal on Jan 29, 2020, 12:36

The IP -> SR -> XPlan -> lab -> ETL pipeline has many potential places where it can break or report errors and warnings. 

Can we automatically track and write this information into the experiment request?

**Comment by tramyn** [comment]
@jakebeal I think this feature is already supported from #198. Could you confirm?

**Comment by mwes** [comment]
The pipelines report back their status into that database table, which is now loaded into the request
