### ISSUE TITLE
"Go" button for executing a run

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#180]
In GitLab by @jakebeal on Jan 29, 2020, 18:22

We want to be able not just to export a structured request, but to have a "go" button that executes a full run at Strateos.

**Comment by mwes** [comment]
In GitLab by @mweston on Jan 29, 2020, 18:25

Document agave message to structured request reactor from Intent Parser python backend (including any TACC dependencies)

**Comment by mwes** [comment]
In GitLab by @dbryce on Mar 25, 2020, 11:17

I'd like this to be a near-term (not immediate) objective.  Before next PI meeting would be nice.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Mar 25, 2020, 16:09

2.6 sounds like the right place for it to stay, then.  The ball is still in @mweston's court to prepare the enabling documentaiton and architecture.

**Comment by mwes** [comment]
In GitLab by @mweston on Apr 28, 2020, 09:20

The main need here is sending a reactor message from the intent-parser python backend to XPlan with its expected input. This would mirror what XPlan is currently sending in its integration test.

https://gitlab.sd2e.org/sd2program/round-trip/blob/development/test/integration/test_srr_xplan.py
https://gitlab.sd2e.org/sd2program/round-trip/blob/development/test/integration/test_submit.py#L186

This includes:
- The ER URL, which we obviously have
- The protocol parameters, which we can support
- XPlan requires a few other things, which we should discuss with @dbryce about filling in. Not all of this may be needed:

- Container ids at Strateos
- Protocol (Growth Curve, Time Series, Obstacle Course) / Protocol-Id
- Number of plates
- Constraints
- Strain property
- Challenge Problem (we could probably look this up for you)

**Comment by mwes** [comment]
In GitLab by @jakebeal on Apr 29, 2020, 07:38

@mweston As you have written this, it sounds like this would require Intent Parser to become aware of the reactor architecture and change to interact with the pipeline on a "push" architecture rather than the current "pull" architecture for the routing of its JSON outputs?  I am wary of a decision like this, because making it dependent on Tapis would inhibit the transitions that we are attempting to set up.

**Comment by mwes** [comment]
In GitLab by @mweston on Apr 29, 2020, 07:47

@jakebeal That's certainly a reasonable concern. Without the intent parser sending any sort of message or data, however, it's unclear to me how such a "Go" button on the interface would be achieved. Would a "Go" button set some internal state in the intent-parser that a looping poll of all possible experiment requests would be querying over every few seconds to see if a user has requested it to run? Something else?

One could certainly architect this in a way that isolates SD2 specific infrastructure if you are concerned about transition:

Go Button -> Start Experiment Request (Interface) -> Start Interface Request (SD2 Implementation) -> Send Reactor Message

**Comment by mwes** [comment]
In GitLab by @jakebeal on Apr 29, 2020, 09:11

Let me propose two possible paths here, either of which I think is workable:

1. The "Go" button isn't actually in the Intent Parser, but in something else that one points at an Experimental Intent document and says "Run this document".  This is what I thought you were intending originally, because you didn't want random users to be able to fire off spurious experiment runs or accidentally duplicate experiments because they thought there was a network problem, etc.
2. The "Go" button is in the intent parser, but instead of invoking a reactor, it invokes a RESTful API for one or more receiving destinations.  That can be hosted in a reactor for SD2, but can be hosted in any other sort of server interface for other deployments.  If we go with this route, however, I'm not sure how you want to deal with the spurious experiments problem.

I think the second might be equivalent to what you said in your message, but I'm not sure if I was reading it correctly.

**Comment by mwes** [comment]
In GitLab by @mweston on Apr 29, 2020, 09:59

I thought this would be a button, or an option in the Intent-Parser drops down that says "Run this experiment at Strateos", e.g. a "Go Button". I can see now that the original issue was unclear on this point, but I am not the only user with input of course. I am glad we are discussing/clarifying this.

For option 1 - we don't need any further support. However, this begs a question as to what the other interface is that hosts such a button. This is the primary interface the program uses to interact with Experiment Requests, so I don't think we should we create another interface. I suggest this "Go Button" functionality should live in the intent-parser. One could even view the status of one's "Go Button" request in the ER itself.

For option 2 - This could work. I see continued concerns about integrating with TACC APIs - e.g. through an interface or otherwise. This is fine - I would just have a function that can POST the above JSON example to a REST endpoint that is not hard-coded in the intent parser backend and we'll take it from there. This might require additional terms in the ER as noted, which we should explore with @dbryce and Josh Nowak.

XPlan and Strateos can handle the issue with spurious or unintended experiments. I would argue constraining execution is outside the scope of this specific issue. A user can submit a request, but it's up to receiving system to accept it.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Apr 29, 2020, 12:55

If you're OK with the submits being open, then we can definitely go with option 2.  Your sketch above fits with what I was thinking.

**Comment by mwes** [comment]
In GitLab by @mweston on Apr 29, 2020, 13:07

Works for me.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Apr 29, 2020, 15:42

I've created a set of issues descending from this decision: #194, #195, #196, and #197.

I'll leave this one open for now to help keep track of the documentation provided about format.

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 11, 2020, 18:16

@jakebeal @mweston I've added my comments to the 4 related issues. Please have a look.

**Comment by mwes** [comment]
In GitLab by @mweston on Jun 12, 2020, 13:54

Responding now

**Comment by jakebeal** [comment]
Closing as transferred into child issues.
