### ISSUE TITLE
Design REST target for "Go" button to invoke

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#195]
In GitLab by @jakebeal on Apr 29, 2020, 15:32

Per discussion on #179, we plan to have a "Go" command in the Intent Parser that can request experiment initiation via a RESTful API.

We will need an appropriate such API designed, such that an instance can be built on the TACC side and a set of invocations be targeted for it on the Intent Paresr side.

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 11, 2020, 18:15

@mweston, do you and/or @dbryce have some procedure/workflow set up to convert a structured request generated from intent parser into something that reactor can used to run an experiment? If so, can we manipulate your setup to define a set of invocations for this TACC "Go" API?

**Comment by mwes** [comment]
In GitLab by @mweston on Jun 12, 2020, 13:53

@tramyn Yes, this is automated from the "intent-parser" down. That is we call the reactor with a message that tells it to process an ER URL. We call the intent-parser, then pass the output to XPlan, which then calls Strateos.

@dbryce We'll need to do some work here. Currently the intent-parser has very little knowledge of some of the Strateos semantics you pass in the current message outside of the parameters. e.g. the following message has the ER URL, but much more information - things like protocol, containers, etc:

```
{
    "xplan_reactor": "xplan",
    "plate_size": 96,
    "protocol": "obstacle_course",
    "plate_number": 2,
    "container_search_string": ["ct1e3qc85mqwbz8", "ct1e3qc85jc4gj5"],
    "strain_property": "SD2_common_name",
    "xplan_path": "data-sd2e-projects.sd2e-project-14/xplan-reactor/NOVEL_CHASSIS/experiments",
    "submit": True,
    "protocol_id": "pr1e5gw8bdekdxv",
    "test_mode": False,
    "experiment_reference_url_for_xplan": "https://docs.google.com/document/d/1rVBMyoh1ajjEJdEhPgNYCkn_E6esoOXZycfiBRLavvA",
    "default_parameters": {
        "exp_info.sample_time": "8:hour",
        "exp_info.overnight_volumes.culture_volume": "15:microliter",
        "exp_info.overnight_volumes.media_volume": "1000:microliter",
        "exp_info.growth_volumes.culture_volume": "15:microliter",
        "reagent_info.base_media": "SC Media",
        "reagent_info.kill_switch": {
            "value": "false",
            "inputs": {
                "false": {}
            }
        },
        "reagent_info.inducer_info": {
            "inputs": {
                "2": {
                    "inducer_1": {
                        "containerId": "ct1dt583rf2xjpa",
                        "wellIndex": 0
                    },
                    "inducer_1_final_conc": {
                        "magnitude": 0.05,
                        "unit": "micromolar"
                    },
                    "inducer_2": {
                        "containerId": "ct1dt583rf2xjpa",
                        "wellIndex": 0
                    },
                    "inducer_2_final_conc": {
                        "magnitude": 0.025,
                        "unit": "micromolar"
                    }
                }
            },
            "value": "2"
        },
        "measurement_info.plate_reader_info": [{
            "read_choice": {
                "value": "fluorescence",
                "inputs": {
                    "fluorescence": {
                        "excitation": "594:nanometer",
                        "emission": "623:nanometer",
                        "gain": 0.25
                    }
                }
            }
        }, {
            "read_choice": {
                "value": "luminescence",
                "inputs": {
                    "luminescence": {
                        "integration_time": "1:second"
                    }
                }
            }
        }],
        "measurement_info.36_hr_read": False,
        "measurement_info.flow_info": {
            "do_flow": {
                "value": "every-sampling",
                "inputs": {
                    "every-sampling": {
                        "flow_params": "bacillus"
                    }
                }
            }
        }
    }
}```

**Comment by mwes** [comment]
In GitLab by @mweston on Jun 15, 2020, 11:40

@tramyn I suggest we start with known arguments, namely:


```
    "xplan_reactor": "xplan",
    "experiment_reference_url_for_xplan": <Url of ER>,
    "default_parameters": {
       <Parsed parameters from IP>
    },
    "submit": True,
    "test_mode": False

```

Is it possible to display this in an editable text box before sending? This would allow the user to fill in the remaining JSON parameters themselves, which the intent parser currently doesn't know about. Things like:

```
    "plate_size": 96,
    "protocol": "obstacle_course",
    "plate_number": 2,
    "container_search_string": ["ct1e3qc85mqwbz8", "ct1e3qc85jc4gj5"],
    "strain_property": "SD2_common_name",
    "xplan_path": "data-sd2e-projects.sd2e-project-14/xplan-reactor/NOVEL_CHASSIS/experiments",
    "protocol_id": "pr1e5gw8bdekdxv"
```

You can target the REST API here:

https://gitlab.sd2e.org/sd2program/experimental-intent-parser/issues/195

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 15, 2020, 14:20

Yes, I can set up something for you to insert JSON parameters but can we not expand the parameter tables in an ER document to include these extra information? Does it not make sense to group these information with the protocol parameters?

**Comment by mwes** [comment]
In GitLab by @mweston on Jun 15, 2020, 14:30

That could work work - these specific parameters would need to go at the top of the JSON message vs. in `default_parameters` (see the example message). If that's something we can do, let's move forward with that.

**Comment by tramyn** [comment]
@mwes how have you been using results generated from IP for parsing information from a parameter table? Are you modifying its content in order to get it in a form that Dan Bryce will need to run protocols with the parameters generated from IP? 

I ask this question because IP follows a specific format in order to generate an output for default parameters. 
If you recall in an old discussion about [parameter tables](https://gitlab.sd2e.org/sd2program/experimental-intent-parser/issues/159), we discussed how IP should generate nested information such as `exp_info.media_well_strings` as a Parameter.  We came up with a solution that for specific fields such as `exp_info.media_well_strings`, IP should generate a flatten representation as its output parameter value. For example, if a user provides a parameter value in this form `Plate Read Gain Configuration` with the values  `0.1, 0.16, 0.2` , then IP generates this type of output :

```
 "plate_reader_info.gain.0": 0.1,
 "plate_reader_info.gain.1": 0.2,
 "plate_reader_info.gain.2": 0.3
```
In this scenario, the output above is specific to IP. Will these output values need to be changed into a different format in order guarantee that IP is sending valid  information for `default_parameters` to TACC's "Go" API?

**Comment by mwes** [comment]
@tramyn this is fine. You should reverse the parameters attributes in the table (via the dictionary mapping), and pass the resulting field name through, like you currently do. We will then either convert for XPlan, or XPlan will be updated to read the hierarchical format. No IP changes related to parameter formatting are required from what I can see.

**Comment by tramyn** [comment]
@mwes Can IP use the data catalog schema to validate an experimental request or is this something that TACC's "Go" API will handle when making a request?

**Comment by mwes** [comment]
@tramyn Good question. Validation occurs automatically upon receipt of the message by the reactor - so no additional validation code or checks need to be written here.

**Comment by tramyn** [comment]
@mwes How does TACC's "Go" API interpret multiple request on the same experiment? I have set up IP to indicate to its user whether their request to execute an experiment was successful by popping up a message dialog box that report the status of their request. However, this type of message will not be as valuable if we have different users calling "Execute Experiment" on the same experiment document if it has already been called by another user 15 minutes prior to its current request. 

How will IP know that a request to execute an experiment has been requested? 
Should IP allow its user to call "Execute Experiment" as many time as the user want and have TACC's "Go" API handle which experimental request it wants to execute?

I think this is where #198 comes in to address this issue but I'm missing the connection here. Could you or @jakebeal fill in my missing gaps?

**Comment by mwes** [comment]
There's no need to enforce or limit this from your API. XPlan has checks and Strateos' API ultimately has the final say in whether it actually gets run or not. If accepted, structured request documents will be created automatically, and will show up in the database (from which the dashboard reads). They will have "submitted" entries, but not upload or ingest until they are actually run.

**Comment by tramyn** [comment]
Okay, then that makes it much simpler for IP to handle. Thanks @mwes for clarifying this last bit of information.
