### ISSUE TITLE
TACC "Go button" target

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#196]
In GitLab by @jakebeal on Apr 29, 2020, 15:33

Following #194, we will need to set up a service on TACC to actually provide an instance of the RESTful API for the "Go button" to invoke.

**Comment by mwes** [comment]
In GitLab by @mweston on Jun 15, 2020, 11:32

This has been stubbed out. You can currently post to the following endpoint, with the target message being worked out in: https://gitlab.sd2e.org/sd2program/experimental-intent-parser/issues/194

e.g. replace the "from_ip" test message below with the populated one above in $194

```
curl -sk -XPOST -H "Content-Type: application/json" -d '{"from_ip": true}' 'https://api.sd2e.org/actors/v2/control-annotator.prod/messages?x-nonce=$NONCE'
```

For authorization you will need to provide a nonce query parameter. I'll send that through a separate channel.

You'll receive back a message:

```
{
  "message": "The request was successful", 
  "result": {
    "_links": {
      "messages": "https://api.sd2e.org/actors/v2/4y3VqqLYRXRBJ/messages", 
      "owner": "https://api.sd2e.org/profiles/v2/sd2eadm", 
      "self": "https://api.sd2e.org/actors/v2/4y3VqqLYRXRBJ/executions/1OqbJ0oglqvOv"
    }, 
    "executionId": "1OqbJ0oglqvOv", 
    "msg": {
      "from_ip": true
    }
  }, 
  "status": "success", 
  "version": "1.5.4"
}
```

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 15, 2020, 14:39

@mweston I tried running the above curl command and this is what I got:
```
{
  "message": "Actor with identifier 'control-annotator.prod' not found", 
  "result": null, 
  "status": "error", 
  "version": "1.5.4"
}
```

Am I suppose to replace `from_ip` with a string representation or a json representation of IP parameter values?

**Comment by mwes** [comment]
In GitLab by @mweston on Jun 15, 2020, 15:16

@tramyn you need to fill in the nonce authorization that I sent you. Specifically the note here about:

"For authorization you will need to provide a nonce query parameter. I'll send that through a separate channel."

`messages?x-nonce=$NONCE`

Replace $NONCE with the string I sent you (or populate that as an environment variable) and it should work.

**Comment by jakebeal** [comment]
Now in @tramyn court with #197, #198
