### ISSUE TITLE
Report experiment status into document

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#198]
In GitLab by @jakebeal on Apr 29, 2020, 15:40

Following #194, we will also want to be able to report the state of an experiment from the pipeline into the document.

This will likely take the form of a "mini-table" that is either immediately above the specification table (e.g., connected with the lab name mini-table) or immediately below the specification table.

For an initial architecture, this might be accomplished by polling the RESTful API at regular intervals (e.g., 5 minutes). In general, that won't scale, however, so eventually it will be better to set up for some form of callback.

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 11, 2020, 18:15

@jakebeal, @mweston 

From what I understand, this new table will be created from issue #196. 
Intent parser will not parse information from this table but rather write information to this table every X minute time interval. Information written to this table will report the current status of an experiment request document. The status reported in this new table is dependent upon information provided in a lab table. 
From there, Intent parser will then perform a request to TACC's "Go" API to get the status for the desired experiment in a given lab. Is this summary correct?

**Comment by mwes** [comment]
In GitLab by @jakebeal on Jun 12, 2020, 09:28

That's correct, modulo the fact that we'd not necessarily execute the write if nothing's changed in the last X minutes.

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 12, 2020, 13:18

@jakebeal What is a specification table in this case?

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 12, 2020, 13:21

mentioned in merge request !119

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 12, 2020, 13:21

created merge request !119 to address this issue

**Comment by mwes** [comment]
In GitLab by @mweston on Jun 12, 2020, 13:58

@tramyn @jakebeal you should review the project dashboard, which currently receives automated updates on the experiment from submission all the way to ingest, ETL, data converge, and pre-computed table processing. The program currently uses this as a single point of reference for the status of an experiment and all of its related states and data products.

https://dash.sd2e.org/queries/40

There are no manual edits here. This system is visualizing a single MongoDB table. That table contains rows for structured requests, which we parse from the intent parser (note the experiment  reference URL). If you want to replicate this kind of information in the document, you could have your Python backend query that table, and populate information from it in the experiment request document.

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 12, 2020, 14:31

@mweston Are there instructions you can point me to for querying this MongoDB table?

**Comment by mwes** [comment]
In GitLab by @mweston on Jun 12, 2020, 15:25

@tramyn sure, this will get you started. I'll send you credentials through a different channel. 

```
import pymongo

dbURI = '<CREDENTIALS_GO_HERE>'

client = pymongo.MongoClient(dbURI)
db = client.catalog_staging

matches = db.structured_requests.find({"experiment_reference_url":"https://docs.google.com/document/d/1fFcxyJyheMrzSsVoSsO6v7qHJKFf_0heIFtqEur02cg", "$where": "this.derived_from.length > 0" })

for match in matches:
    print(match)
```

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 18, 2020, 00:56

@mweston will you evaluate this mock up [status table](https://docs.google.com/document/d/1GJydNCNmiTTyf8m5LjBfEhMblLvaCincK8SBwbsg1t4/edit) and let me know if the contents in this table is of interest for a user to check on the status of an experiment?

**Comment by mwes** [comment]
In GitLab by @mweston on Jun 18, 2020, 08:23

Yes, this is a good start. There's other information in the database table that folks use that you'll want to pull out as well:

Overnight Growth
Recovery Loops
The path to the structured request

and most importantly the experiment id(s). A single ER can produce multiple experiment ids when it is interpreted and executed by Strateos and and XPlan

ex.

![image](/uploads/adcc285db594d4a1a25f89c320a9ba5c/image.png)

There are additional links to ETL products such as FLOW and RNASeq, but I suggest we tackle those later.

**Comment by tramyn** [comment]
@mwes could you document what this status report mean? It's not clear to me what each of these fields represent.

**Comment by mwes** [comment]
Sure: https://schema.catalog.sd2e.org/schemas/structured_request.json

Status is a dictionary of keys (these are enumerated), each of which can contain a `path` (Agave path, or string of catalog/catalog_staging/unspecified), `state` (boolean), and `last_updated` (date-time)

This tells us when certain states are achieved by the pipeline: submitted to the lab, uploaded, converted, annotated, ingested, and so on. Each step can succeed or fail, is timed, and has a a location to its output or product. They should be self-explanatory, but here's a description:

"xplan_request_submitted" - When the experiment was submitted to the lab.
"uploaded": - When the experiment was uploaded by the lab
"converted": - When the lab trace was converted
"mtypes": - The state is a string that contains an encoding of the measurementt ypes ("PF--" means Plate Reader and Flow)
"comparison_passed": - Whether the annotated lab trace passed metadata comparison
"annotated": - When the lab trace was annotated
"ingested": - When the annotated lab trace was ingested
"etl_flow": - When FLOW ETL was run, links to color model and job outputs
"obs_load": - When the ingested experiment observations were loaded




The ETL keys have additional links to ETL products such as FLOW and RNASeq, but I suggest we tackle those later.

**Comment by tramyn** [comment]
@mwes To implement this request, IP expect that an experiment_id must be specified within a lab table in order to generate the desired status table. If this information is not provided in an experiment document, then IP has no way of knowing what status table to insert to the document. I have tried looking through this [ER folder](https://drive.google.com/drive/folders/1FYOFBaUDIS-lBn0fr76pFFLBbMeD25b3) and it doesn't look like any of these documents have experiment_ids specified in a lab table. However, I do see that these experiment_ids are recorded in the golden files that I have been using for testing IP. Can we update the actual experiment documents to mirror the contents that are recorded in the golden files? 

Also, as a side note and question, this template referred to [here](https://docs.google.com/document/d/1GJydNCNmiTTyf8m5LjBfEhMblLvaCincK8SBwbsg1t4/edit?ts=5f03580c) assumes that an experiment document will have one status table. Will an experiment document ever have more than one status table?

**Comment by mwes** [comment]
@tramyn Recall that ER does not know/cannot know the experiment ids ahead of time here. These are controlled and produced by Strateos after XPlan processes the resulting SR. The query I provided above will resolve to the correct child SRs this ER URL produces, which will include the experiment id(s) you need: https://github.com/SD2E/experimental-intent-parser/issues/198#issuecomment-646840850

Note there can be more than one result, hence the loop - a single ER can produce multiple lab experiment runs. This prevents the need for the ER author to provide these values, as we can resolve them from the database. 

RE: multiple status tables, this is a good question note: https://github.com/SD2E/experimental-intent-parser/issues/198#issuecomment-646840882  "and most importantly the experiment id(s). A single ER can produce multiple experiment ids when it is interpreted and executed by Strateos and and XPlan". Each experiment row has its own status, which in this form will result in multiple tables.

**Comment by tramyn** [comment]
@mwes Oh right. Then the template that we have [here](https://docs.google.com/document/d/1GJydNCNmiTTyf8m5LjBfEhMblLvaCincK8SBwbsg1t4/edit) should be good to follow off of. Specifically, the key here is to have IP update the lab table with an experiment_id and an experiment status property to connect information between a lab table and an experiment status table. Then, this will open up opportunities for users to look at multiple status tables with different experiment_ids. This approach will assume that there can never be more than one lab table with the same lab name in a Experiment document.

**Comment by mwes** [comment]
@tramyn are you expecting the user to fill the below out or to programmatically generate it? With the above query, you can generate it (and the resulting status table), which my recommendation. The lab is not unique - e.g. Transcriptic can appear multiple times. Experiment id values are unique.


```
Lab: Transcriptic
--
Experiment_id: abc
Experiment_status: Table 3
```

**Comment by tramyn** [comment]
@mwes I was thinking of the latter (programmatically generate it) to fill in experiment_id and experiment_status to a lab table. But, now I'm not sure I understand why a lab name is not unique to an experiment. What information can I get differently if a lab can appear multiple times but with different experiment_ids?

**Comment by mwes** [comment]
Yes, the experiment_id is unique, but both of them come from the same ER, and were run by the same lab.
