### ISSUE TITLE
Google Doc with multiple intent parser addon will not use the latest addon install

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#201]
In GitLab by @tramyn on May 19, 2020, 19:41

There are a number of Google Docs that have been found with multiple versions of intent parser addon. In this condition, it is unclear how a Google Doc decides which version of intent parser it will run on. This is problematic when we make a new release of intent parser with new features that are built for the GUI. In this scenario, a user will not be able to access a new feature unless we filter through every app script bounded to a document and delete all the necessary app scripts until the document binds to correct version. There isn't an API call that will allow us to programmatically remove this. There is however, an [app script project](https://script.google.com/home/my) that can be install on a user Google account to perform app script deletion. This will involve locating each app script by name and manually delete each file. 

Another solution is to go over each google document that intent parser is installed on and record all the script ids that are not bounded to a given document and add it to intent parser's deployment procedure. If we decide to go with this approach, we will need to define an alternative way of recording how document ids are assigned to its corresponding script id.

**Comment by mwes** [comment]
In GitLab by @tramyn on May 21, 2020, 17:34

@jakebeal [Here](https://docs.google.com/spreadsheets/d/1JcTjlN7bpo-O2XPz5NUPS1KBmhOm6aLuunIHPUffg3Y/edit#gid=0) is a list of documents that have incorrect version of intent parser binding to a Google Document. I have gone through the list and remove versions of intent parser that are considered obsolete. Notice that there are three tabs in this spreadsheet. Novel Chassis and Protein Design tabs still has documents with versions of intent parser that will need to be removed. These documents are color coded in red. Because I will need ownership of these files to delete these addons, I have contacted owners of these documents to get these permission.

**Comment by mwes** [comment]
In GitLab by @tramyn on Jun 10, 2020, 15:29

Moving to 2.7 release. Was able to fix a number of documents but there are still 14 documents that rely on others to provide me ownership access to these files to make the necessary fix.

**Comment by jakebeal** [comment]
There are only three recent document remaining; the others are too old to likely be significant.
We have added notes to these documents that say that they will not be fixed unless the owner transfers and requests a fix. Closing this issue for now as sufficiently resolved and ball no longer in our court.
