### ISSUE TITLE
Improve performance to Analyze/Suggestion functions 

### ISSUE THREAD

**Issue by tramyn** [SD2E/experimental-intent-parser#209]
Look into improving performance for analyzing/suggesting linked terms to SBH.

**Comment by mwes** [comment]
NC attempting to use SBH lookups in: https://docs.google.com/document/d/1QqJbcCXTasAgm0_0_i1wRyZLt7wL-oK5ol6slV6syYk/edit#

https://sd2e.slack.com/archives/C931AH9LY/p1596748757364900?thread_ts=1596730558.356800&cid=C931AH9LY

Enoch Yeung 
@mark.weston - we ran into issues with the linking of reagents with the SBH URIs.  After running the “analyze from cursor” step, it fails to search  on SynBioHub

**Comment by YeungRepo** [comment]
Here is a screenshot of the error: 

![image](https://user-images.githubusercontent.com/10078713/89584480-fd4c9980-d7f0-11ea-82c8-5cd75c1bf682.png)

We ended up populating all the links manually, but for broad user adoption, I suggest we get the linking functionality working.  The structured request generation is working well! Thanks Mark and Tramy!

**Comment by tramyn** [comment]
@YeungRepo @mwes , responding to say that this is valid and reproducible. Will look into this issue and will address for 2.8 milestone.
