### ISSUE TITLE
Make tables with optional features visible to users

### ISSUE THREAD

**Issue by tramyn** [SD2E/experimental-intent-parser#212]
IP supports a variety of features that are accessible by adding optional fields to tables within an experiment request document. However, these optional fields are not visible in a document to alert a user of what their options are unless the user is creating the table for the first time by accessing the IP's drop down menu. We should explore features (action items) that are supported in Google Doc to help make these optional fields visible. One suggestion is to use comments. We should look into this and support whichever feature that will best represent this information.

**Comment by jakebeal** [comment]
(Note, this issue is only for Measurement Tables and Control Tables; Parameter Tables will be addressed via by #250)

**Comment by tramyn** [comment]
For this feature request, a sidebar is used to show what are the required and optional fields available for table templates provided by IP. There is an interest in using comment boxes so issue #262 was created to support this feature.
