### ISSUE TITLE
Intent Parser 2.7 Generation Failing in Production

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#219]
I can't seem to run the intent parser for _most_ experiment requests:

Examples that fail (I can produce many more of these if you need more examples, just let me know):
http://intentparser.sd2e.org/document_request?1fFcxyJyheMrzSsVoSsO6v7qHJKFf_0heIFtqEur02cg
http://intentparser.sd2e.org/document_request?1D9hXd5Hmeb75FGH0sGq93KjCOjHKD26x8HXluNJLII8

Examples that succeed:
http://intentparser.sd2e.org/document_request?13tJ1JdCxL9bA9x3oNxGPm-LymW91-OT7SRW6fHyEBCo

The failures are all returning back 502 Bad Gateways. Can you confirm? Any ideas? What is the current testing suite reporting?

![image](https://user-images.githubusercontent.com/5033275/88747916-c2c26d00-d11d-11ea-810d-e88a20f5218d.png)

**Comment by tramyn** [comment]
@mwes This error occurred because IP's docker image did not include this commit (c30f6c1 ) in the build. I had to rebuild IP a new image to include it. This problem should be resolved. Please confirm.

**Comment by mwes** [comment]
Thanks @tramyn confirm fixed.
