### ISSUE TITLE
Some inducer concentrations not parsing correctly

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#233]
ER: https://docs.google.com/document/d/1QqJbcCXTasAgm0_0_i1wRyZLt7wL-oK5ol6slV6syYk

Some inducer concentration sequences do not correctly parse with units

We updated the ER in the meantime to include leading zeroes for floats, and turn integer like units into floats (e.g. 26 -> 26.0)

When provided:
Xylose
26, 13, 6.5, 3.25, 1.625, .8125, .40625, .203125, .1015625, 0.05078125 mM

The mM unit is not parsed through:
ex.
"name": {
    "label": "Xylose",
    "sbh_uri": "https://hub.sd2e.org/user/sd2e/design/Xylose/1"
},
"value": "6.5"

**Comment by mwes** [comment]
Some Slack discussion: https://sd2e.slack.com/archives/GP34M2C02/p1597769159046300

**Comment by tramyn** [comment]
@mwes In the slack thread, you mentioned that you had to insert a leading 0 to some of the decimal values to get it working. This is the main reason why IP was unable to parse through "26, 13, 6.5, 3.25, 1.625, .8125, .40625, .203125, .1015625, 0.05078125 mM". IP does not define a decimal value such as (.8125) as a valid value. I've expanded IP to interpret this. 

I plan on releasing 2.8 sometime today and this will include this fix. 
Let me know if this will be an issue for you.

**Comment by mwes** [comment]
@tramyn yes, please *_do not_* release 2.8 today. It has known, breaking changes that downstream consumers of the IP (our structured request reactor, XPlan) need to handle. We can perform this work on the staging intentparser2 instance you've provided. If this is released into production before we can handle those changes, all automated experimentation will immediately come to a stop.

See: 
https://github.com/SD2E/experimental-intent-parser/issues/207
https://github.com/SD2E/experimental-intent-parser/issues/205
