### ISSUE TITLE
Include parameter fields to SBOL Dictionary 

### ISSUE THREAD

**Issue by tramyn** [SD2E/experimental-intent-parser#242]
Currently, IP have the following fields hardcoded into its tool when parsing parameter tables.  

- plate_size
- plate_number
- container_search_string
- strain_property
- xplan_path
- protocol_id

But since IP is set up to rely on the dictionary to map parameter fields from its common name to its equivalent Transcriptic UID,  the tool will break if these fields do not have mappings. Most of the parameter fields are already in the dictionary so this will make sense if we map these additional fields in the dictionary as well.

**Comment by mwes** [comment]
@tramyn no problem, I've added attributes  to the SBOl dictionary for this

**Comment by tramyn** [comment]
@mwes Could you also add to the dictionary this name `experiment_reference_url_for_xplan`?

**Comment by mwes** [comment]
@tramyn Sure thing - done.

**Comment by tramyn** [comment]
@mwes one more term... `xplan_base_dir`

**Comment by mwes** [comment]
@tramyn sure, done.
