### ISSUE TITLE
Support annotations on what media spike-ins are possible for a factor of type “sample”

### ISSUE THREAD

**Issue by tramyn** [SD2E/experimental-intent-parser#243]
XPlan needs to know what media spike-ins are possible for a factor of type “sample” from an ER document. 
However, IP does not have a place to specify this information. 
This slack thread [here](https://sd2e.slack.com/archives/C931AH9LY/p1597946570001700?thread_ts=1597946391.001000&cid=C931AH9LY) records information about this discussion. 
The idea is to have  IP allow this information to be annotated as a row wise constraint on a measurement table. 
@danbryce mentioned that the generated from IP should take on this form:
```
"Kanamycin_additive": {
                "name": "Kanamycin_additive",
                "domain": [
                    0, 128
                ],
                "dtype": "float",
                "otype": "DesignElement",
                "ftype": "sample"
            },
```
@mwes proposed additional structures that will be supported from his end (maybe in data catalog) to readily support this feature for @danbryce. As such, contact @mwes to follow up on his proposed data structure to address this feature request for IP.

**Comment by danbryce** [comment]
This issue is OBE at this point.  We were planning on treating these reagents as media spike-ins, but decided to do them as inducers.  This feature may become important in the future.

**Comment by jakebeal** [comment]
Closing for now as OBE. @danbryce please reopen again if it becomes important in the future.
