### ISSUE TITLE
Unable to process certain Parameter Tables with raw JSON text

### ISSUE THREAD

**Issue by tramyn** [SD2E/experimental-intent-parser#245]
There are parameter fields in this [ER document](https://docs.google.com/document/d/1YKACI6n5_AYc-RF5oAuZDnBlJxMwMnx9K5yDKuckamA) that will not correctly translate hard coded json text into JSON object. Running "Generate Structured Request" will return broken json value into a random list of string values.

**Comment by mwes** [comment]
Sorry for the assignment issues - I was trying to query for any issues assigned to me 😅

**Comment by tramyn** [comment]
Resolved issue by flagging parameter field: `Induction reagents media, culture, and volume` to read in its assigned parameter value as JSON.
