### ISSUE TITLE
Allow script to run automatically

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#25]
In GitLab by @jakebeal on Feb 1, 2019, 21:19

It would be nice if at least some functions of the script could run automatically, rather than having to be run manually.

**Comment by mwes** [comment]
In GitLab by @jakebeal on Jan 29, 2020, 12:44

Particularly of interest:

- Reporting pipeline status and data availability
- Reporting build progress
- Validation of ER table

**Comment by tramyn** [comment]
@jakebeal could you update your request for this feature? Which of these interest are still needed from intent parser? From what I understand, I think reporting build request is the most active request that needs support. The two other requests seems supported.

> In GitLab by @jakebeal on Jan 29, 2020, 12:44
> 
> Particularly of interest:
> 
> * Reporting pipeline status and data availability
> * Reporting build progress
> * Validation of ER table

**Comment by jakebeal** [comment]
Reporting experiment status (per #198) has a menu item associated with it --- is it also updating automatically?  If so, it should have a date-stamp noting when it has last been updated, and whether the update is automatic or manual.

Validating the ER table also appears to solely manual right now.

**Comment by tramyn** [comment]
IP has a [script](https://github.com/SD2E/experimental-intent-parser/blob/develop/intent_parser/addons/sync_experiment_status_table.py) set up to automatically update experiment statuses for each ER document. This script is currently hosted on portainer and had 2 successful runs for the past two days now. This script does not, however, include a date-stamp in the documents to report when it was last updated and if the update was manual or automatic. We can include these feature in this issue. 

As for validating ER tables automatically, yes you're right--there is no automatic script that will perform validation on all ER documents. We can set up a separate script to run this type of job. Who should IP report failed or successful validations for this automatic run?

**Comment by jakebeal** [comment]
For ER table validations, I'd say to just start by marking it in the document above the table or in the micro-table just before it that has the lab name, e.g., something like "passed [manual/automatic] validation on DATE-TIME"

**Comment by tramyn** [comment]
@jakebeal I've created issue #235 to address :

> For ER table validations, I'd say to just start by marking it in the document above the table or in the micro-table just before it that has the lab name, e.g., something like "passed [manual/automatic] validation on DATE-TIME"

**Comment by jakebeal** [comment]
Closing, as it is now replaced by the sub-issues.
