### ISSUE TITLE
Report more error messages to run request an experiment execution

### ISSUE THREAD

**Issue by tramyn** [SD2E/experimental-intent-parser#250]
IP needs more error reports to guide a user through the process to successfully request an experiment execution. Although IP does report a level of errors to the user, more detailed information will be useful. 

Messages to consider reporting:
- report fields that needs to be set
- report actual and expected results

**Comment by jakebeal** [comment]
One of the things that is needed is to be able to distinguish between optional and required parameters in order to validate a request. We also need to be able to know what type of values are required for each of these parameters and their default values.

This should be solved by providing an OPIL protocol specification.

**Comment by jakebeal** [comment]
@danbryce Can you please say what else you would like to see for this issue? We will then be splitting things into sub-issues.

**Comment by jakebeal** [comment]
@pleaderlee Can you & Josh please work with @rmarkelo on providing OPIL specs for Strateos protocols, as this will be necessary to solve this issue.

**Comment by jakebeal** [comment]
@danbryce reports that the default tables inserted also sometimes have extra parameters or are missing parameters. This is also something that should be solved via OPIL.

**Comment by tramyn** [comment]
From this discussion, below are areas that will need to be addressed for this issue:
1. what is required vs. option
2. not knowing type of value for parameter
3. missing parameter. Specifically, not always getting parameters that are expected from a specified protocol

**Comment by tramyn** [comment]
#256 addresses :
> 1. what is required vs. option

Both issues #255 and #256 addresses the following. Specifically, look at the contents returned from calling Strateos's API for the a parameter's value type.
> 2. not knowing type of value for parameter

#255 addresses :
> 3. missing parameter. Specifically, not always getting parameters that are expected from a specified protocol
