### ISSUE TITLE
Update intent parser execution target

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#252]
@tramyn we will likely need to update the intent parser's execution target for requesting to execution an experiment. Instead of calling the reactor directly with the message and nonce, we'll need to follow an authentication step which will authenticate the requesting user on TACC. Matt, Dan, and I are working through this (see below for a draft of our current thinking).

This authentication step is required so that the user is 1) authenticated and has permissions to execute through the reactor chain, up until Strateos execution 2) XPlan will retrieve this user's Strateos credentials for execution from an internal TACC store. This prevents the need to specify or store any sort of credentials in the ER, or process them through the IP.

This will expand XPlan usage beyond just a single user, allowing other SD2 users to author, process, and execute experiment requests without any direct assistance from Dan Bryce or TA4.

![image](https://user-images.githubusercontent.com/5033275/92756839-2bc31480-f35b-11ea-8668-2f8e923ce9cc.png)

This is a work in progress, and I'll keep you updated on what changes, if any, you need to make. Comments/discussion is of course welcome.

**Comment by tramyn** [comment]
@mwes This sounds straightforward and thanks for keeping me updated. I'll continue to follow this discussion. If there are slack channels opening up for this then please let me know so I can stay up to date.

**Comment by mwes** [comment]
@tramyn sure - the main discussions are in the open under #ip-sr-xplan and #cyberinfrastructure

**Comment by tramyn** [comment]
Base on Slack's ip-sr-xplan thread discussion with @mwes,  there is a new authentication layer added when requesting an experiment execution. IP will need to update its endpoint to the link mentioned in the Slack thread. The HTML content received from this response will provide users the ability to authenticate their experiment request. IP will then need to have a new tab open to display this HTML content.

**Comment by mwes** [comment]
@tramyn per our discussion on 9/22 this should be ready to test. Is it possible to create a build that points to the new POST target? This should be a small change, and we can then see if it is working correctly, or if we need to make any changes/updates to the TACC authentication gateway.

**Comment by tramyn** [comment]
@mwes I ran into authentication issue when using clicking on the interface returned from TACC. I'll give you a more in depth summary after #277 is resolved.

**Comment by mwes** [comment]
OK, I've updated #277 What was the issue?

**Comment by mwes** [comment]
FYI Matt V. just reminded me that with today's maintenance, TACC systems will likely be throwing auth errors - we should wait until Corral is back online and the maintenance completes, then we can re-rest. This should be done ~Wednesday 12:00 CST. I had forgotten about the maintenance - thank you for checking! I expect we will be able to make more progress tomorrow.

**Comment by mwes** [comment]
@tramyn maintenance should be complete - can you test again?

**Comment by tramyn** [comment]
@mwes I can confirm that authentication is working for the new endpoint. However, I'm getting HTTP 400 error when connecting this feature to #257 . This is the message that I am getting "Actor with identifier 'control-annotator.prod' not found". Could you confirm if TACC's server was able to receive my request? I can provide you the Execution ID on slack and follow up from there.

**Comment by mwes** [comment]
Sure, please send the Execution ID.
