### ISSUE TITLE
Validate strains in Controls Table

### ISSUE THREAD

**Issue by tramyn** [SD2E/experimental-intent-parser#254]
Currently, IP will only validate strains for measurement tables. IP does not check the validity of strains when processing controls table. This means, users can add any strain value to a controls table and IP will process that without checking if it exists within the SBOL dictionary. It would be desirable if IP could include this level of validation when processing strains under a control's table as well.

**Comment by mwes** [comment]
Thanks @tramyn. Please include the same validation and output steps as we do for measurements strains. e.g. we currently generate for a controls table "W303" strain value (text) that links to "https://hub.sd2e.org/user/sd2e/design/W303/1":

```
"strains": ["W303"]
```

which is ambiguous/underspecified, leading to some of the confusion that prompted this issue.

Instead, if we treat this the same as a measurement strain, we should emit the fully specified strain value:

```
"strains": [{
        "sbh_uri": "https://hub.sd2e.org/user/sd2e/design/W303/1",
        "label": "W303",
        "lab_id": "name.transcriptic.W303"
    }]
```
