### ISSUE TITLE
Remove optional fields when creating a default Parameter table

### ISSUE THREAD

**Issue by tramyn** [SD2E/experimental-intent-parser#256]
IP does not have a clear notion for generating required vs. optional default parameters when creating a Parameter table from IP's drop down menu item. IP should be filtered through to differentiate this. Right now, IP can get this type information when pulling information from Strateos's API by looking at the presence of a “required” field (https://developers.transcriptic.com/docs/input-types).  From here, IP should be updated so only required information are set when creating default parameter table. Users can then add in optional fields to their parameter table after the creation of the table.

**Comment by jakebeal** [comment]
Consider also two other alternatives:

1. Adding them as options in the creation dialogue
2. Adding them in, but with a default value of "optional" (or similar marking), and the user can then delete the row or leave it blank if they wish.

**Comment by tramyn** [comment]
Implementation is setup to go off of alternative 1.

> Consider also two other alternatives:
> 
> 1. Adding them as options in the creation dialogue
