### ISSUE TITLE
Support additional columns for measurement table

### ISSUE THREAD

**Issue by tramyn** [SD2E/experimental-intent-parser#277]
include new columns:
- Number of Negative Controls: a list of integers
- Use RNAse Inhibitor in Reaction: a boolean value
- DNA Reaction Concentration: a list of integers
- Template DNA: a list of strings

**Comment by tramyn** [comment]
@mwes do you have a placeholder described in data catalog for these new fields?

**Comment by mwes** [comment]
Same as before - just have the columns natively parse as contents (should require almost no changes on the IP side I believe)
