### ISSUE TITLE
Generate OPIL from Measurement table

### ISSUE THREAD

**Issue by tramyn** [SD2E/experimental-intent-parser#282]
to completely transition a SR to OPIL, IP will need to generate OPIL from a measurement table

**Comment by tramyn** [comment]
@jakebeal I'm not sure that generating OPIL from a measurement table is the right thing to do here. I recall in one of our old discussions, we talked about using SBOL3's combinatorial derivation object to encode this information. Is this correct? If not, what type of OPIL Parameter object does this fall under? A `MeasureParameter`?

**Comment by jakebeal** [comment]
@tramyn  This isn't the `Parameter` objects of OPIL, but the `sampleSet` properties, which point to SBOL3 `CombinatorialDerivation` objects in the UML diagrams.  So yes, you're right that it should be `CombinatorialDerivation`, and I'm right that this is included in the OPIL structures. :-)
