### ISSUE TITLE
Issue generating new golden files from intentparser2.sd2e.org

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#286]
I am encountering a validation error while generating new SR golden file content against intentparser2.sd2e.org

1. https://docs.google.com/document/d/1fFcxyJyheMrzSsVoSsO6v7qHJKFf_0heIFtqEur02cg / YeastSTATES 1.0 Growth Curves Request : Works

2. https://docs.google.com/document/d/1Mba6kqDila4W32Z46NEqXZFx868A3O36I9GIVOvMQ70 / YeastSTATES 1.0 Time Series Round 1: Fails generation from IP with errors. This looks like either an issue with a control or a measurement entry timepoints value - not generating as an array per schema? This is as before - the only desired change here was expanding the current "strain" definition beyond its current single string value:

https://gitlab.sd2e.org/sd2program/cp-request/blob/master/input/structured_requests/YeastSTATES%201.0%20Time%20Series%20Round%201.json#L84

```
{
	'errors': ["{'value': 0.0, 'unit': 'hour'} is not of type 'array'&#13;&#10;&#13;&#10;Failed validating 'type' in schema['properties']['runs']['items']['properties']['measurements']['items']['properties']['controls']['items']['properties']['timepoints']:&#13;&#10;    {'items': {'$ref': '#definitions/timepoint'},&#13;&#10;     'minItems': 1,&#13;&#10;     'type': 'array'}&#13;&#10;&#13;&#10;On instance['runs'][0]['measurements'][0]['controls'][0]['timepoints']:&#13;&#10;    {'unit': 'hour', 'value': 0.0}"]
}
```

**Comment by tramyn** [comment]
@mwes I made a new build. Could you try running these two documents again using intentparser2.sd2e.org? 

> 1. https://docs.google.com/document/d/1fFcxyJyheMrzSsVoSsO6v7qHJKFf_0heIFtqEur02cg / YeastSTATES 1.0 Growth Curves Request : Works

The first file is failing in IP's golden file testing because the SBOL dictionary has a duplicate entry for `Plate reader fluorescence emission frequency`. The json file that you've generated is mapping the SR output to 
```
'plate_reader_info.fluor_em': '530:nanometer',
'plate_reader_info.fluor_ex': '488:nanometer',
``` 

while IP is generating this as the output:

```
'plate_reader_info.emission': '530:nanometer',
'plate_reader_info.excitation': '488:nanometer',
```

This second file should run successfully. I will need this json file updated and reran in IP.
> 2. https://docs.google.com/document/d/1Mba6kqDila4W32Z46NEqXZFx868A3O36I9GIVOvMQ70 / YeastSTATES 1.0 Time Series Round 1: Fails generation from IP with errors. This looks like either an issue with a control or a measurement entry timepoints value - not generating as an array per schema? This is as before - the only desired change here was expanding the current "strain" definition beyond its current single string value:

**Comment by mwes** [comment]
Deleted duplicate mappings for plate_reader_info.emission/excitation

**Comment by mwes** [comment]
@tramyn Thanks, re-generated and merged: https://gitlab.sd2e.org/sd2program/cp-request/merge_requests/571

**Comment by tramyn** [comment]
Thank you @mwes. golden files are passing!
