### ISSUE TITLE
Intent parser generation/validation returns error without revealing the underlying problem, but the REST API does

### ISSUE THREAD

**Issue by mwes** [SD2E/experimental-intent-parser#295]
ER: https://docs.google.com/document/d/162OXD2SacWUb4aN1WK7vA2rlKupmcstDpPheAt49ADQ

Running "Generate Structured Request" or "Validate Structured Request" returns an error - the generation or validation failed, but we don't know why/cannot figure out what to do to correct it.

<img width="663" alt="Screen Shot 2020-12-01 at 11 54 12 AM" src="https://user-images.githubusercontent.com/5033275/100771690-b7819580-33cc-11eb-88ab-51c427ee7972.png">

However, if we go directly through the REST API: http://intentparser.sd2e.org/document_request?162OXD2SacWUb4aN1WK7vA2rlKupmcstDpPheAt49ADQ

We can see it's a validation error for the field Induction reagents media, culture, and volume, and we can correct it. Is there a reason this isn't being surfaced?

```
{
	"errors": [
		["Parameter table has invalid Parameter Value: {\"inducers\" : ... is an invalid json format."]
	]
}
```

**Comment by tramyn** [comment]
@mwes I am unable to reproduce this error. Running  "Generate Structured Request" and "Validate Structured Request" passes on my end. Can you try reproducing this error to see if this is still a problem?

**Comment by mwes** [comment]
@tramyn yes @meslami-netrias fixed the issue so we could make progress on this. To reproduce it, just ensure the JSON is invalid - drop a comma, brace, etc.
