### ISSUE TITLE
opil returned from generateOpilRequest missing value_of assignments

### ISSUE THREAD

**Issue by jgladwig** [SD2E/experimental-intent-parser#320]
It looks like the opil returned from generateOpilRequest is missing the `value_of` data for all of its parameter value objects. If I understand correctly the `value_of` entry is supposed to point back to the Parameter object which the ParameterValue object is storing a value for.

For example I am expecting the BooleanValue in the below ttl to have an entry like this:
```
ns1:valueOf <http://strateos.com/GrowthCurve/BooleanParameter1> ;
```

ttl:
```
...

<http://strateos.com/GrowthCurve/BooleanParameter1> a ns1:BooleanParameter,
        sbol:Identified ;
    ns1:defaultValue <http://strateos.com/GrowthCurve/BooleanParameter1/BooleanValue2> ;
    sbol:displayId "BooleanParameter1" ;
    sbol:name "submit" .

<http://strateos.com/GrowthCurve/BooleanParameter1/BooleanValue2> a ns1:BooleanValue,
        sbol:Identified ;
    ns1:value true ;
    sbol:displayId "BooleanValue2" .

...
```

I am hoping to do some reasoning about the contents of the ExperimentalRequest object in the returned document but I think I will need that `value_of` entry in order to get the full picture. Without it I think I am unable to track the values back to their associated parameters.

**Comment by jakebeal** [comment]
Note: there is a kludge workaround at present, but we shouldn't rely on it.
