### ISSUE TITLE
Install instructions links to python-datacatalog in a private repo

### ISSUE THREAD

**Issue by jamesscottbrown** [SD2E/experimental-intent-parser#339]
The README says to install python-datacatalog from the [sd2e gitlab instance](https://gitlab.sd2e.org/sd2program/python-datacatalog), which is private.

It should probably link to the [mirror on GitHub](https://github.com/SD2E/python-datacatalog) instead, assuming this is reasonably up-to-date.

**Comment by mwvaughn** [comment]
The mirror is kept synced to Gitlab on every commit.

**Comment by mwes** [comment]
@tramyn it looks like that README.md is out of date - we should update it, along with the requirements.txt so we can resolve these dependencies automatically instead of with manual steps.
